# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:
# Input: s = "", t = "y"
# Output: "y"

s = "abcd"
t = "abcde"
for i in t:
    if t.count(i) > s.count(i):
        print(i)
        break 


# For s = "abcd" and t = "abcde", the loop processes each character:
# For "a", "b", "c", "d", t.count("a") equals s.count("a"), so it moves to the next character.
# For "e", t.count("e") > s.count("e") (1 > 0), so "e" is printed.
# for 2nd :
# The if condition checks if t.count("y") > s.count("y").
# Since 1 > 0 is true, the code inside the if block is executed.